name: 개발환경 배포

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy_dev:
    name: Deploy Dev
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy-pipeline.yml
    with:
      environment: dev
